services:
  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    container_name: agregator_app
    ports: 
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

volumes:
  postgres_data: {}